### ISSUE TITLE
Roast me better 

### ISSUE THREAD

**Issue by officialasishkumar** [TherkuTech/Leetcode-Roaster-Backend#3]
wtf is this? Roast me better

"congratulations on being alive for 33 days straight! I'm impressed that you managed to solve 53 hard problems, which is roughly 1.6 problems per month. Your '50 Days' and '100 Days' badges are more like participation trophies, considering you can't even manage a single streak without collapsing. With a total of 375 problems solved, I'm assuming you've been solving the same easy problems over and over again. Keep it up, and you might just become the next LeetCode champion... of doing the bare minimum!"

**Comment by aswathcm29** [comment]
It's kinda reverse roasting Asish 😅
